#!/bin/bash

cd Bellhop

if [[ "$HOST" == "sverdrup"* ]] ; then
    ln -s ../optfiles/Makefile_ifort Makefile
elif [[ "$OSTYPE" == "darwin22.0" ]] ; then
    ln -s ../optfiles/Makefile_gfortran Makefile
fi

make all
