!                           DISCLAIMER
! 
!   This file was generated by TAF version 5.9.12
! 
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
! 
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
! 

subroutine f_ad( a, x, x_ad, y, y_ad )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare arguments
!==============================================
real, intent(in) :: a
real, intent(in) :: x
real, intent(inout) :: x_ad
real, intent(out) :: y
real, intent(inout) :: y_ad

!----------------------------------------------
! FUNCTION AND TAPE COMPUTATIONS
!----------------------------------------------
y = a*x**4

!----------------------------------------------
! ADJOINT COMPUTATIONS
!----------------------------------------------
x_ad = x_ad+4*y_ad*a*x**3
y_ad = 0.

end subroutine f_ad

subroutine f( a, x, y )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 5.9.12  **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare arguments
!==============================================
real, intent(in) :: a
real, intent(in) :: x
real, intent(out) :: y

y = a*x**4
end subroutine f

