!                           DISCLAIMER
! 
!   This file was generated by TAF version 6.4.7
! 
!   FASTOPT DISCLAIMS  ALL  WARRANTIES,  EXPRESS  OR  IMPLIED,
!   INCLUDING (WITHOUT LIMITATION) ALL IMPLIED  WARRANTIES  OF
!   MERCHANTABILITY  OR FITNESS FOR A PARTICULAR PURPOSE, WITH
!   RESPECT TO THE SOFTWARE AND USER PROGRAMS.   IN  NO  EVENT
!   SHALL  FASTOPT BE LIABLE FOR ANY LOST OR ANTICIPATED PROF-
!   ITS, OR ANY INDIRECT, INCIDENTAL, EXEMPLARY,  SPECIAL,  OR
!   CONSEQUENTIAL  DAMAGES, WHETHER OR NOT FASTOPT WAS ADVISED
!   OF THE POSSIBILITY OF SUCH DAMAGES.
! 
!                           Haftungsbeschraenkung
!   FastOpt gibt ausdruecklich keine Gewaehr, explizit oder indirekt,
!   bezueglich der Brauchbarkeit  der Software  fuer einen bestimmten
!   Zweck.   Unter  keinen  Umstaenden   ist  FastOpt   haftbar  fuer
!   irgendeinen Verlust oder nicht eintretenden erwarteten Gewinn und
!   allen indirekten,  zufaelligen,  exemplarischen  oder  speziellen
!   Schaeden  oder  Folgeschaeden  unabhaengig  von einer eventuellen
!   Mitteilung darueber an FastOpt.
! 

subroutine f_ad( n, x, x_ad, y, y_ad )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.4.7   **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare arguments
!==============================================
integer, intent(in) :: n
real, intent(in) :: x
real, intent(inout) :: x_ad
real, intent(out) :: y
real, intent(inout) :: y_ad

!==============================================
! declare local variables
!==============================================
real :: a
real :: a_ad
real :: h
real :: h_ad
integer :: i
integer :: i2

!----------------------------------------------
! RESET LOCAL ADJOINT VARIABLES NO ALLOC
!----------------------------------------------
a_ad = 0.
h_ad = 0.

!----------------------------------------------
! FUNCTION AND TAPE COMPUTATIONS
!----------------------------------------------
a = x
h = 1.
do i = 1, n
  h = a*sin(h)
end do
y = h

!----------------------------------------------
! ADJOINT COMPUTATIONS
!----------------------------------------------
h = 1.
h_ad = h_ad+y_ad
y_ad = 0.
do i = n, 1, -1
  h = 1.
  do i2 = 1, i-1
    h = a*sin(h)
  end do
  a_ad = a_ad+h_ad*sin(h)
  h_ad = h_ad*a*cos(h)
end do
x_ad = x_ad+a_ad
a_ad = 0.

end subroutine f_ad

subroutine f( n, x, y )
!******************************************************************
!******************************************************************
!** This routine was generated by Automatic differentiation.     **
!** FastOpt: Transformation of Algorithm in Fortran, TAF 6.4.7   **
!******************************************************************
!******************************************************************
implicit none

!==============================================
! declare arguments
!==============================================
integer, intent(in) :: n
real, intent(in) :: x
real, intent(out) :: y

!==============================================
! declare local variables
!==============================================
real :: a
real :: h
integer :: i

a = x
h = 1.
do i = 1, n
  h = a*sin(h)
end do
y = h
end subroutine f
